[package]
name = "project"
version = "0.1.0"
edition = "2021"

[dependencies]
# client
clap = { version = "4.5.21", features = ["derive"] }
reqwest = { version = "0.12.9", features = ["json"] }
tokio = { version = "1.41.1", features = ["rt", "rt-multi-thread", "macros"] }
