[package]
name = "project"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
env_logger = "0.11.5"
log = "0.4.22"
rocket = "0.5.1"
serde = "1.0.215"
serde_json = "1.0.133"
sysinfo = "0.32.0"

[lib]
name = "lib"
path = "src/lib.rs"


[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "chunk"
path = "src/chunk/chunk.rs"
